[package]
name = "ferredge-runtime-tokio"
description = "Tokio runtime and network adapters for ferredge core traits"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[features]
default = []
runtime = ["dep:tokio", "ferredge-core/std", "ferredge-core/runtime"]
net = ["dep:tokio", "ferredge-core/std", "ferredge-core/net"]
serial = [
    "dep:tokio",
    "dep:tokio-serial",
    "dep:serialport",
    "ferredge-core/std",
    "ferredge-core/serial",
]

[dependencies]
ferredge-core = { workspace = true }
tokio = { workspace = true, optional = true }
tokio-serial = { workspace = true, optional = true }
serialport = { workspace = true, optional = true }
